export default class Session {
    private readonly _roomUUID: string;               // room to join
    private readonly _clientUUID: string;             // unique id generated by the server

    constructor() {
        this._roomUUID = "";
        this._clientUUID = "";
    }

    /**
     * Returns the room's id
     */
    public get roomUUID(): string {
        return this._roomUUID;
    }

    /**
     * Returns the current client's id from the WebSocket server
     */
    public get clientUUID(): string {
        return this._clientUUID;
    }
}