import {Socket} from "socket.io-client";

export default class Session {
    private readonly _socket: Socket;
    private readonly _roomUUID: string;               // room to join
    private readonly _clientUUID: string;             // unique id generated by the server

    constructor(socket: Socket) {
        this._socket = socket;
        this._roomUUID = "";
        this._clientUUID = "";
    }

    /**
     * Returns the room's id
     */
    public get roomUUID(): string {
        return this._roomUUID;
    }

    /**
     * Returns the current client's id from the WebSocket server
     */
    public get clientUUID(): string {
        return this._clientUUID;
    }

    /**
     * Returns the socket
     */
    public get socket(): Socket {
        return this._socket;
    }
}